model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: phi
    litellm_params:
      model: ollama/phi
      api_base: http://vait-ollama-cpu:11434


litellm_params:
  drop_params: True

router_settings:
  num_retries: 2
  # Allow 2 fails before marking a model as down
  allowed_fails: 2
  # Set a 1 minute timeout
  timeout: 60
